### ISSUE TITLE
The path containing ':' in the url cannot be properly proxied

### ISSUE THREAD

**Issue by KagurazakaNyaa** [sonatype/nexus-public#205] opened 2023-07-29 07:17 UTC
502 bad gateway when accessing `/FreeBSD:13:amd64/23.1` when proxying https://pkg.opnsense.org after updating from 3.56 to 3.58
Try it in other raw-proxy repo, and find that as long as `:` is included in the first-level path name, you will definitely get a 502 error
The log reports an error `org.sonatype.nexus.orient.raw.internal.RawProxyFacet - Exception org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: FreeBSD:13:amd64/. checking remote for update, proxy repo opnsense failed to fetch FreeBSD:13:amd64/., content not in cache.`
At the same time, I traced the network request on the proxy server log and found that when such an error occurs, nexus does not actually send out the request

**Comment by nblair** [comment] 2023-08-01 19:54
Thanks for opening this @KagurazakaNyaa - we'll investigate further.

**Comment by nblair** [comment] 2023-11-30 16:42
Hi @KagurazakaNyaa - we've completed our investigation on this and unfortunately it's got a tricky answer. The presence of a colon in the first path segment results in an invalid URI per [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.3). Looking at the root directory of pkg.opensense.org, it looks like they have a number of folders that violate the spec.

Our HTTP internals reject the outbound request due to this invalid URI, which results in the error you are seeing.

If the colon containing folders on pkg.opensense.org where nested one path segment further, e.g. https://.../something-here/FreeBSD:10:amd64/, the proxy would work in Nexus Repository right off the bat. I don't have a workaround to suggest at present, unless perhaps you could somehow proxy that URL with the appropriate nesting, and target the proxy instead?

**Comment by KagurazakaNyaa** [comment] 2023-12-01 02:18
I looked up RFC 3986 about the restrictions on characters that can be used in URIs, and I noticed that the restriction you mentioned in the first segment that the `:` character cannot be used in path components does not apply to absolute path URIs.
A URI similar to https://pkg.freebsd.org/FreeBSD:14:amd64/ should be valid.
The situation you mentioned that the first segment cannot contain `:` should be the situation described in https://www.rfc-editor.org/rfc/rfc3986#section-4.2 in relative-path reference.

**Comment by nblair** [comment] 2023-12-21 14:39
Great news @KagurazakaNyaa - the team has found a path forward. Our fix is deployed internally and I can confirm I am able to successfully create a raw proxy for the host you've listed here and access all the content underneath.
The fix will be delivered in release 3.64.0 which will be released to the public on January 9. It will be listed under the release notes as NEXUS-40771.

Thanks!

**Closed by nblair** 2023-12-21 14:39 UTC
Labels: bug, enhancement

**Comment by VladimirDe** [comment] 2024-02-18 13:02
Please, take a look at https://github.com/sonatype/nexus-public/issues/340
