### ISSUE TITLE
NEXUS-40119 - NullPointerException in BearerTokenManager if docker credentials contain special characters

### ISSUE THREAD

**Issue by flako-dd** [sonatype/nexus-public#227] opened 2023-08-18 07:48 UTC
Hi!

The system has been updated from 3.41.1 to 3.59.0 using the docker image: [nexus-oss 3.59.0](https://hub.docker.com/layers/sonatype/nexus3/3.59.0/images/sha256-919ec9845bd0432ff345044f50b3b1696d92321b458ecd942dbdc7908192ea16?context=explore) on docker-ce EL7 with the default DB.

docker logins fails if the password contains a `&` and/or `[` characters. (see log below)
the same password works in this version via the web interface and is otherwise valid and worked before upgrading.
The user is a local user with docker permissions.

to reproduce:
```shell
docker login -u thedockeruser -p "aPassWithAn&AndOra[char" https://docker.mycompany.com/
```
Changing the password to an alphanumeric one solves the issue.

Looking the the [changelog for nexus-oss 3.59.0](https://help.sonatype.com/repomanager3/product-information/release-notes/2023-release-notes/sonatype-nexus-repository-3.59.0-release-notes) i assume this issue might have been introduced in this version. but i did not analyze this deeper.

```log
2023-08-18 00:12:53,795+0000 WARN  [qtp1150036514-3328]  thedockeruser org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/docker/v2/token?account=thedockeruser&scope=repository%3Aess%2Fjava-11-openjdk-centos%3Apull&service=https%3A%2F%2Fdocker.mycompany.com%2Fv2%2Ftoken
java.lang.NullPointerException: null
	at java.lang.String.<init>(String.java:166)
	at org.sonatype.nexus.security.token.BearerTokenManager.createToken(BearerTokenManager.java:60)
	at org.sonatype.nexus.repository.docker.internal.security.DockerTokenManager.authenticate(DockerTokenManager.java:58)
	at org.sonatype.nexus.repository.docker.internal.security.DockerTokenManager$authenticate.call(Unknown Source)
	at org.sonatype.nexus.repository.docker.internal.V2Handlers$_closure19.doCall(V2Handlers.groovy:394)
	at sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy205.handle(Unknown Source)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
	at org.sonatype.nexus.repository.view.Context.start(Context.java:179)
	at org.sonatype.nexus.repository.view.Router.dispatch(Router.java:65)
	at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:52)
	at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:43)
	at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.dispatchAndSend(ViewServlet.java:212)
	at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.doService(ViewServlet.java:174)
	at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.service(ViewServlet.java:126)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:96)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:112)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:96)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:112)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.repository.httpbridge.internal.ExhaustRequestFilter.doFilter(ExhaustRequestFilter.java:80)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:116)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:79)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:101)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by letcinodie** [comment] 2023-08-21 08:12
I get the same issue, but with anonymous pulling of docker images. no auth required, so no special char in the credentials.
I had to rollback to 3.58

**Comment by nblair** [comment] 2023-08-22 19:46
Thanks @flako-dd for opening an issue. We will investigate internally and report back.

**Comment by akumlehn** [comment] 2023-08-30 07:23
We also ran into this issue. Any confirmation and/or plans to address this?

**Comment by matthias-onpier** [comment] 2023-08-30 07:26
we have the same issue with the github oauth plugin. the github tokens always have a "_" inside which triggers the same exception during login. so everyone using this plugin will probably have the same issue.

**Comment by igloo15** [comment] 2023-09-18 20:47
I am also running into this same issue at my company. Also with anonymous pulling of images so no credentials and on version 3.59. Thinking about rolling back to 3.58 as others have suggested.

**Comment by pekiZG** [comment] 2023-09-19 10:30
@igloo15 or you can push to 3.60 and change credentials to not have special characters (if possible);

**Comment by igloo15** [comment] 2023-09-19 17:05
@pekiZG Which credentials do I need to change for anonymous docker image pulling?

**Comment by patajones** [comment] 2023-09-22 11:33
I'm having the same issue here. Doing an anonymous pull on a Docker repository. Using version 3.60.0.

**Comment by patajones** [comment] 2023-09-22 13:32
> I'm having the same issue here. Doing an anonymous pull on a Docker repository. Using version 3.60.0.

As there was no workaround available, I had to downgrade to version 3.58. 

Could you change the title to indicate that the error also occurs with anonymous pulls? @nblair

**Comment by wlucha** [comment] 2023-09-22 13:38
I'm having the same issue, cannot pull with anonymous anymore. using v3.60.0

**Comment by igloo15** [comment] 2023-09-26 19:17
@nblair Should we make a separate issue related to anonymous docker pulls or will this issue cover both?

**Comment by X4mp** [comment] 2023-10-02 12:25
I'm having the same issue, cannot pull with anonymous anymore. using version v3.60.0

**Comment by mperochon** [comment] 2023-10-03 15:51
I'm having the same issue on version 3.60,  cannot pull with anonymous anymore.

**Comment by patajones** [comment] 2023-10-03 19:41
Today, version 3.61.0 was released (https://help.sonatype.com/repomanager3/product-information/release-notes/2023-release-notes/sonatype-nexus-repository-3.61.0-release-notes), but I haven't had a chance to verify if the issue still persists. However, the bug number reported by @nblair (NEXUS-40119) is not listed as fixed in the release notes.

**Comment by nblair** [comment] 2023-10-03 19:58
Hey everyone, thanks for confirming the issue is still present. @patajones is correct, this item is not yet fixed in the 3.61.0 release that went out today. We are working on prioritization, I do not yet have a fix date as the work as not started.

**Comment by nblair** [comment] 2023-10-03 20:03
@letcinodie @igloo15 @mperochon @X4mp do you have any errors in your logs that coincide with failed attempts to pull anonymously? If so, do they match @flako-dd 's sample in the original report, or are they different?

**Comment by patajones** [comment] 2023-10-06 17:59
> @letcinodie @igloo15 @mperochon @X4mp do you have any errors in your logs that coincide with failed attempts to pull anonymously? If so, do they match @flako-dd 's sample in the original report, or are they different?

In my logs, I am observing the exact same error as mentioned in the original report by @flako-dd, with the only difference being that I am performing anonymous pulls.

**Comment by mperochon** [comment] 2023-10-07 18:27
> @letcinodie @igloo15 @mperochon @X4mp do you have any errors in your logs that coincide with failed attempts to pull anonymously? If so, do they match @flako-dd 's sample in the original report, or are they different?

Same error than the original report

**Comment by igloo15** [comment] 2023-10-10 15:11
I agree with the others that the error is the same. The only difference is that instead of "thedockeruser" I have just "null" there which is probably because its anonymous and not from any user.

**Comment by nblair** [comment] 2023-10-10 20:14
I have to admit I'm having a hard time replicating the error - in a pretty much default OSS deployment, I'm able to authenticate successfully via `docker login` with local users that have the aforementioned special characters.

I'm sorry if this is a silly ask, but can you each confirm that you have the "Docker Bearer Token Realm" in the Active list, as shown here:

![Screenshot 2023-10-10 at 2 52 48 PM](https://github.com/sonatype/nexus-public/assets/1041730/fe6d7187-b41f-487a-8d11-3ac3e2029cb5)

It's required for docker login to work correctly.

**Comment by igloo15** [comment] 2023-10-11 14:04
@nblair This issue has nothing to do with `docker login`. That is why I asked if we should make a separate issue. The problem we are having is with **anonymous** docker pulling. To reproduce you simply have to do `docker logout` and then try to do a `docker pull`. 

I have the bearer token properly setup and the anonymous settings checked. In fact I haven't changed any setting since 3.58 which is when things were last working. Then suddenly in 3.59 it stopped working without changing anything. If I docker login and try to pull it works fine.

**Comment by nblair** [comment] 2023-10-11 18:13
Thanks all for confirming. @flako-dd thanks for helping pin down that this only seems to appear on migrated users. Now I'm closer to replicating. @igloo15 it may not seem like it, but internally anonymous is a form of authentication and hops down the same code path. This is all helpful, I'll keep investigating.

**Comment by jraubswitch** [comment] 2023-10-23 19:01
We had this same issue but it seems the `Anonymous Access` Role was changed to `Crowd Realm` . could this have been during the upgrade? When I changed it back to `Local Authenticating Realm` it works as intended

**Comment by letcinodie** [comment] 2023-11-27 11:50
Hi everyone, following the [guide to reset the admin password](https://support.sonatype.com/hc/en-us/articles/213467158-How-to-reset-a-forgotten-admin-password-in-Sonatype-Nexus-Repository-3), via orientdb console, I tried recreating the anonymous user and resetting the default security realms.

I wasn't successful and, after a restart, the "Default Role Realm is enabled but not configured" error popped up in the Status page.
[Adding the "Default Role" capability to "nx-anonymous" finally fixed the issue](https://help.sonatype.com/repomanager3/nexus-repository-administration/access-control/default-role).

I can now pull docker images anonymously again.
Not sure if this is the correct procedure, but hopefully it will help finding an official solution.

**Closed** 2024-01-10 16:24 UTC
Labels: bug
