### ISSUE TITLE
./mvnw clean install failed

### ISSUE THREAD

**Issue by zhucan** [sonatype/nexus-public#234] opened 2023-08-28 06:03 UTC
```
[ERROR] Tests run: 9, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.034 s <<< FAILURE! - in org.sonatype.nexus.common.io.SafeXmlTest
[ERROR] testStrictDocumentBuilderFactory(org.sonatype.nexus.common.io.SafeXmlTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: (an instance of org.xml.sax.SAXParseException and exception with message a string containing "DOCTYPE is disallowed")
     but: exception with message a string containing "DOCTYPE is disallowed" message was "将功能 "http://apache.org/xml/features/disallow-doctype-decl" 设置为“真”时, 不允许使用 DOCTYPE。"
Stacktrace was: org.xml.sax.SAXParseException; systemId: file:/var/folders/m0/k57ygmwd74xcrgs7wfvqw0qr0000gn/T/junit1238325722982985681/junit9033076240617268955.tmp; lineNumber: 2; columnNumber: 10; 将功能 "http://apache.org/xml/features/disallow-doctype-decl" 设置为“真”时, 不允许使用 DOCTYPE。
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.sonatype.nexus.common.io.SafeXmlTest.testStrictDocumentBuilderFactory(SafeXmlTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by nblair** [comment] 2023-08-29 19:46
Hi @zhucan thanks for opening an issue. Can you provide some clarity on what you are trying to do?

**Comment by zhucan** [comment] 2023-08-30 02:11
I want to compile the nexus manually and run it.

**Comment by nblair** [comment] 2023-09-01 13:59
I'm unable to replicate the error you are observing, I'm able to get a clean build against dde318dce1. Are you using Java 8?

**Comment by zhucan** [comment] 2023-09-02 16:09
yes, I'm using the java 8

**Comment by nblair** [comment] 2023-09-05 19:30
Hi @zhucan, you haven't really given us enough detail in your report here for us to take any action, nor can we reproduce the failure you are reporting. I'm going to close this as cannot reproduce.

**Closed by nblair** 2023-09-05 19:30 UTC
Labels: incomplete

**Comment by zhucan** [comment] 2023-09-13 02:34
@nblair Is there a doc for build nexus-public?

**Comment by n454149301** [comment] 2023-12-08 08:17
I am a Chinese person, and I encountered the same issue, which seems to be caused by language encoding. Using "LANG=en_US.UTF-8 LANGUAGE=en ./mvnw clean install" can compile successfully. However, when using "LANG=zh_CN.UTF-8 LANGUAGE=zh_CN ./mvnw clean install," the error mentioned above is reported.
