### ISSUE TITLE
Allow file size limits for Helm yaml files to be configurable

### ISSUE THREAD

**Issue by evansmurithi-hj** [sonatype/nexus-public#283] opened 2023-10-27 06:47 UTC
I want to be able to increase the size limit for Helm yaml files from 25MB to something I'd set myself to support proxying [Bitnami's full index.yaml](https://github.com/bitnami/charts/blob/archive-full-index/bitnami/index.yaml) which is currently at ~25.4MB.

Presently, when using a helm proxy to Bitnami's full index repository, we get the following error:

```
com.fasterxml.jackson.databind.JsonMappingException: The incoming YAML document exceeds the limit: 25165824 code points.
 at [Source: (InputStreamReader); line: 670316, column: 1] (through reference chain: com.sonatype.repository.helm.internal.metadata.ChartIndex["entries"]->java.util.LinkedHashMap["opensearch"]->java.util.ArrayList[3])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3785)
        at com.sonatype.repository.helm.internal.metadata.IndexYamlAbsoluteUrlRewriterSupport.updateUrls(IndexYamlAbsoluteUrlRewriterSupport.java:55)
        at com.sonatype.repository.helm.internal.metadata.IndexYamlAbsoluteUrlRewriter.lambda$2(IndexYamlAbsoluteUrlRewriter.java:67)
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
        at org.sonatype.nexus.thread.io.StreamCopier.lambda$2(StreamCopier.java:148)
        at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
        at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
        at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 25165824 code points.
 at [Source: (InputStreamReader); line: 670316, column: 1]
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:435)
        at com.fasterxml.jackson.core.base.ParserMinimalBase.skipChildren(ParserMinimalBase.java:240)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1133)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        ... 21 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 25165824 code points.
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:317)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:639)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:172)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:429)
        ... 29 common frames omitted
```

**Comment by mbecca** [comment] 2023-10-30 22:44
Hello, I'm having the same issue :(

**Comment by nblair** [comment] 2023-10-31 18:40
Hi @evansmurithi-hj and @mbecca - thanks for opening an issue. What versions of Nexus Repository are you running?

The root cause of that error came from a change to the Jackson library we are using internally. In the upcoming 3.62.0 release, available the first week of November, we've updated the Jackson library to a new version that has a high limit that corrects the issue.

**Comment by mbecca** [comment] 2023-10-31 18:48
> 3.62.

Hi, My version is 3.61.0

**Comment by evansmurithi-hj** [comment] 2023-10-31 19:17
Hi! Yeah, same here, running version 3.61.0. Glad to hear it's going to be fixed in the next release :heart:

**Comment by nblair** [comment] 2023-12-21 17:49
Update on this - we actually have a fix in place that you can use with your current version 3.61.0! No upgrade is required, the root cause is fixed by something delivered in an earlier version.

We have a feature flag that you will need to use in order to proxy this special case asset.

Add the following to your `sonatype-work/nexus3/etc/nexus.properties` file:

```
nexus.helm.yaml.max.bytes=26820410
```

The default value for this property is about 25 MB (`25165824`). When I download the full archive index.yaml, my host reports it has a file size of exactly `26820409` bytes. The above value is one byte higher.

With this property in place (and a restart to make sure it's picked up), I can successfully proxy this file.
If this file grows over time, you may need to adjust the value upwards. 

This property exists because in order to properly proxy helm yaml files, Nexus Repository needs to parse the content and rewrite values contained within. This requires parsing the full contents of the file in memory _at the time the file is first proxied and persisted in Nexus Repository_.

Having this default limit in place is intended to safeguard your system from runaway memory consumption. Keep in mind that increasing this property may result in additional heap memory pressure if you expect to proxy many unique helm index.yaml files of this size concurrently.

**Closed by nblair** 2023-12-21 17:49 UTC
Labels: bug, in-progress

**Comment by Ragatzino** [comment] 2024-03-18 21:12
Hello when was this introduced? I am having the issue on an older release and don't feel like i can upgrade safely to upper versions ^^. I'm on 3.45.0-01.
